services:
  profitei:
    image: profitei
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.local
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  postgres:
  rabbitmq:

networks:
  default:
    driver: bridge