services:
  profitei:
    image: profitei
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env.local
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: RecipePassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'

volumes:
  postgres:

networks:
  default:
    driver: bridge