apiVersion: batch/v1
kind: Job
metadata:
  name: migration-db-job
  namespace: profitei
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: migration-db-job
        image: evmartinelli/profitei-db:latest
        command: ["/bin/sh", "-c", "npx prisma migrate deploy"]
        envFrom:
        - secretRef:
            name: profitei-secrets-hcgg58tb25
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 0
