apiVersion: batch/v1
kind: Job
metadata:
  name: migration-db-job
  namespace: postgresql
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: migration-db-job
        image: evmartinelli/profitei-db:latest
        command: ["/bin/sh", "-c", "npx prisma migrate deploy"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-secret
                key: dburl
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 0
