apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitei-api
spec:
  selector:
    matchLabels:
      app: profitei-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: profitei-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: profitei-api
        image: evmartinelli/profitei
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: profitei-secrets-m2dbm22549
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi" 
            cpu: "200m"
            ephemeral-storage: "1Gi"
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 4
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: x-api-key
              value: 402c2470-cf86-46ad-bb95-ab4025e0fba2
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 4
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: x-api-key
              value: 402c2470-cf86-46ad-bb95-ab4025e0fba2
        env:
          - name: FIREBASE_ADMIN_SDK
            value: "/var/secrets/google/key.json"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-url-secret
                key: dburl
        volumeMounts:
          - name: google-cloud-key
            mountPath: "/var/secrets/google"
            readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
