apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitei-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profitei-api
  template:
    metadata:
      labels:
        app: profitei-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: profitei-api
        image: evmartinelli/profitei
        envFrom:
        - secretRef:
            name: profitei-secrets
        ports:
        - containerPort: 3000
