apiVersion: apps/v1
kind: Deployment
metadata:
  name: profitei-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profitei-api
  template:
    metadata:
      labels:
        app: profitei-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: profitei-api
        image: evmartinelli/profitei
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            memory: "500Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: profitei-secrets
        ports:
        - containerPort: 3000
