apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: profitei-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profitei-api
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
