apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- hpa.yaml

namespace: profitei

# secretGenerator:
# - envs:
#   - .env
#   files:
#   - FIREBASE_ADMIN_SDK=./profitei-net-firebase-adminsdk-pd39h-908588975a.json
#   name: profitei-secrets


images:
- name: evmartinelli/profitei
  newName: evmartinelli/profitei
  newTag: latest
- name: evmartinelli/profitei:latest
  newName: evmartinelli/profitei
  newTag: e18e42ce6c439fde3b2c9064b0fdc188d2368bee
