apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- hpa.yaml

namespace: profitei


images:
- name: evmartinelli/profitei
  newName: evmartinelli/profitei
  newTag: latest
- name: evmartinelli/profitei:latest
  newName: evmartinelli/profitei
  newTag: 5759c7a18c155481e619e70067401afde8aa335c
