apiVersion: v1
data:
  API_KEY: IjQwMmMyNDcwLWNmODYtNDZhZC1iYjk1LWFiNDAyNWUwZmJhMiI=
  MP_ACCESS_TOKEN: IlRFU1QtNjQ4NzI2NDk2NTQ5NDA0Mi0wNDA2MTQtZDdjZDlhYzM1Y2M2NjU5MjQ5MDFmYjUzN2IyNGQyMWMtMTA1NDg3ODE5MSI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"API_KEY":"IjQwMmMyNDcwLWNmODYtNDZhZC1iYjk1LWFiNDAyNWUwZmJhMiI=","DATABASE_URL":"InBvc3RncmVzOi8vcmVjaXBlOlJlY2lwZVBhc3N3b3JkQGxvY2FsaG9zdDo1NDQ0L3JlY2\nlwZSI=\n","MP_ACCESS_TOKEN":"IlRFU1QtNjQ4NzI2NDk2NTQ5NDA0Mi0wNDA2MTQtZDdjZDlhYzM1Y2M2NjU5MjQ5MDFmYj\nUzN2IyNGQyMWMtMTA1NDg3ODE5MSI=\n"},"kind":"Secret","metadata":{"annotations":{},"name":"profitei-secrets-ch656gh8tb","namespace":"profitei"},"type":"Opaque"}
  creationTimestamp: "2024-04-16T00:50:05Z"
  name: profitei-secrets-ch656gh8tb
  namespace: profitei
  resourceVersion: "707084"
  uid: 2693b79f-d0f7-4702-9467-5da5ea67f76e
type: Opaque
