name: Push Docker and Execute Database

on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  check-changed:
    runs-on: ubuntu-latest
    outputs:
      changed-files-database: ${{ steps.changed-files.outputs.any_changed }}
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            prisma/**
            .github/**
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: evmartinelli
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            evmartinelli/profitei:${{ github.sha }}
            evmartinelli/profitei:latest
  build:
    name: Build
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: imranismail/setup-kustomize@v2
      - run: |
          kustomize edit set image evmartinelli/profitei:latest=evmartinelli/profitei:${{ github.sha }}
          git add .
          git commit -m "Set `profitei` image tag to `${GITHUB_SHA}`"
          git push

  # execute-database:
  #   needs: check-changed
  #   runs-on: ubuntu-latest
  #   env:
  #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
  #   if: needs.check-changed.outputs.changed-files-database == 'true'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Run production migration
  #       run: npm run prisma:deploy
