name: Push Docker and Execute Database

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-changed:
    runs-on: ubuntu-latest
    outputs:
      changed-files-database: ${{ steps.changed-files.outputs.any_changed }}
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            prisma/**
            .github/**
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: evmartinelli
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            evmartinelli/profitei:${{ github.sha }}
            evmartinelli/profitei:latest
  build:
    name: Build
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: imranismail/setup-kustomize@v2
      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image evmartinelli/profitei:latest=evmartinelli/profitei:${{ github.sha }}
          cat kustomization.yaml
      
      - name: commit
        run: |          
          git config --global user.email "gh@action.com"
          git config --global user.name "GH Actions"
          git commit -am "Set 'profitei' image tag to '${{ github.sha }}'"
          git push
  docker-database:
    runs-on: ubuntu-latest
    needs: check-changed
    if: needs.check-changed.outputs.changed-files-database == 'true'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: evmartinelli
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.database
          platforms: linux/amd64,linux/arm64
          tags: |
            evmartinelli/profitei-db:${{ github.sha }}
            evmartinelli/profitei-db:latest
  execute-database:
    needs: [check-changed, docker-database]
    runs-on: ubuntu-latest
    if: needs.check-changed.outputs.changed-files-database == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Connect to Kubernetes cluster
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Run database migration
        run: |
          kubectl apply -f k8s/database-job.yaml
